name: Run-Tests
on: push

jobs:
  test:
    runs-on: windows-2022
    strategy:
      matrix:
        unity-version: 
          - 2019.4.31f1
          - 2022.3.6f1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Run tests
        uses: sokuhatiku/unity-test-runner@52b336a8c9e31ac6c7c867e48791dac1fdf1c79c
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unity-version }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}